"""Giao diện luồng nhị phân chung cho relay TLS và DataChannel DTLS."""

from typing import Protocol


class BinarySocket(Protocol):
    @property
    def host_ticket(self) -> str: ...
    @property
    def closed(self) -> bool: ...
    async def send(self, payload: bytes) -> None: ...
    async def receive(self) -> bytes: ...
    async def close(self) -> None: ...


class DirectHost(Protocol):
    @property
    def joiner_count(self) -> int: ...
    def request(self, payload: bytes) -> None: ...
    async def close(self) -> None: ...
